FROM registry.access.redhat.com/ubi9/ubi:latest

# Install GCC, GCC-C++ and make libraries for build environment
# Then clean caches
RUN yum --disableplugin=subscription-manager update -y \
    && yum --disableplugin=subscription-manager install -y \
        gcc \
        gcc-c++ \
        make \
    && yum --disableplugin=subscription-manager clean all
